version: '3'
services:
    web:
        image: nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./web:/var/www/html" 
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"           
        ports:
            - 8080:80
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysql
    php:
        image: nanoninja/php-fpm:latest
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
    composer:
        image: composer
        volumes:
            - ".:/app"
        command: install
    adminer:
        image: adminer
        ports:
            - 8081:8080
        environment:
            - ADMINER_DEFAULT_SERVER=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysql
    mysql:
        image: mysql:${MYSQL_VERSION}
        restart: always
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"